let courses = [
  {
    id: 1,
    source: "male.png",
    Name: "Jhon",
    MemberId: "2143400",
    skill: ["React", "Angular", "C"],
    gender: "Male",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 2,
    Name: "Pakhi",
    MemberId: "2143401",
    source: "female.jpg",
    skill: ["React", "Java", "js"],
    gender: "Female",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 3,
    Name: "Shyam",
    source: "male.png",
    MemberId: "2143402",
    skill: ["Node Js", "Angular", "js"],
    gender: "Male",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 4,
    Name: "Jadhu",
    MemberId: "2143403",
    source: "male.png",
    skill: ["React", "Angular", "My Sql"],
    gender: "Male",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 5,
    Name: "Madhu",
    MemberId: "2143404",
    source: "male.png",
    skill: ["Python", "Ruby", "JS"],
    gender: "Male",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 6,
    Name: "Puja",
    MemberId: "2143405",
    source: "female.jpg",
    skill: ["React", "go", "js"],
    gender: "Female",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 7,
    Name: "Vola",
    MemberId: "2143406",
    source: "male.png",
    skill: ["R", "Angular", "MatLab"],
    gender: "Male",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 8,
    Name: "Rimi",
    MemberId: "2143407",
    source: "female.jpg",
    skill: ["HTML", "Java", "C"],
    gender: "Female",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 9,
    Name: "Khoka",
    source: "male.png",
    MemberId: "2143408",
    skill: ["React", "Vue", "js"],
    gender: "Male",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
  {
    id: 10,
    Name: "Rina",
    MemberId: "2143409",
    source: "female.jpg",
    skill: ["C", "Java", "C++"],
    gender: "Female",
    Project: "Cognizant Internal",
    HCM: "Alex",
  },
];

// console.log(JSON.stringify(courses));
localStorage.setItem("courses", JSON.stringify(courses));
// let ram = localStorage.getItem("courses");
// console.log(ram);
// let ananda = JSON.parse(ram)[0];
// console.log(ananda.skill[0]);
